Fix missing <stddef.h> includes
This patch fixes tons of compilation errors like this on 64-bit Fedora:

/home/penberg/libcpu/libcpu/idbg.cpp:231:15: error: ‘ptrdiff_t’ does not name a type

Signed-off-by: Pekka Enberg <penberg@kernel.org>